# Generated by Django 6.0 on 2025-12-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('usuario', 'mes_referencia')},
        ),
    ]
