# Generated by Django 6.0 on 2025-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancel_effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
