# Generated by Django 6.0 on 2026-01-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_cancel_effective_from_user_cancel_requested_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PTSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario", models.DateTimeField()),
                ("duracao_min", models.PositiveIntegerField(default=60)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        limit_choices_to={"role": "cliente"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        limit_choices_to={"role": "instrutor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_sessions_dadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("instrutor", "horario")},
            },
        ),
    ]
