# Generated by Django 5.2.8 on 2026-01-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ptsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
